theme = "mana"
baseURL = 'https://suzumi-nagata.github.io/'
languageCode = 'en-us'
languageName = "English"
title = "Suzumi's little web corner"
[caches]
[caches.images]
dir = ':cacheDir/images'

[params]
description = "My personal little chunk of the web"
favicon = "favicon.png"

heroTitleLine1 = "Suzumi's little"
heroTitleLine2 = "Web Corner"

math = true

[params.avatar]
assetPath = "images/chibi-miso-transparent.png"
[params.avatar.home]
assetPath = "images/chibi-miso-transparent.png"
[params.avatar.about]
assetPath = "images/chibi-breeze-feather.png"

[params.social]
github = "https://github.com/suzumi-nagata"
linkedin = "https://www.linkedin.com/in/suzumi-nagata"
email = "suzumi.nag@gmail.com"

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[[menus.main]]
name = 'Garden'
url = '/garden/'
weight = 35

[[menus.main]]
name = 'About'
url = '/about/'
weight = 40

[outputs]
  home = ["HTML", "JSON"]

[markup]

[markup.tableOfContents]
startLevel = 1
endLevel = 6
ordered = false

[markup.goldmark]

[markup.goldmark.parser]
# Enable block-level attributes for blockquotes
[markup.goldmark.parser.attribute]
block = true
title = true

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.extensions]
[markup.goldmark.extensions.passthrough]
enable = true
[markup.goldmark.extensions.passthrough.delimiters]
block = [['\[', '\]'], ['$$', '$$']]
inline = [['\(', '\)']]